//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyKTXEntities : DbContext
    {
        public QuanLyKTXEntities()
            : base("name=QuanLyKTXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblCTHoaDon> tblCTHoaDons { get; set; }
        public virtual DbSet<tblHoaDon> tblHoaDons { get; set; }
        public virtual DbSet<tblKhoDoNoiThat> tblKhoDoNoiThats { get; set; }
        public virtual DbSet<tblKiemTraPhong> tblKiemTraPhongs { get; set; }
        public virtual DbSet<tblLoaiChiPhi> tblLoaiChiPhis { get; set; }
        public virtual DbSet<tblNguoiDung> tblNguoiDungs { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblNhatKyTruyCap> tblNhatKyTruyCaps { get; set; }
        public virtual DbSet<tblPhanPhong> tblPhanPhongs { get; set; }
        public virtual DbSet<tblPhong> tblPhongs { get; set; }
        public virtual DbSet<tblSinhVien> tblSinhViens { get; set; }
        public virtual DbSet<tblTang> tblTangs { get; set; }
        public virtual DbSet<tblThongKeDoanhThu> tblThongKeDoanhThus { get; set; }
        public virtual DbSet<tblToaNha> tblToaNhas { get; set; }
        public virtual DbSet<tblViPham> tblViPhams { get; set; }
        public virtual DbSet<tblYeuCauBaoTri> tblYeuCauBaoTris { get; set; }
        public virtual DbSet<tblYeuCauThuePhong> tblYeuCauThuePhongs { get; set; }
    }
}
