//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCTHoaDon
    {
        public int MaCTHD { get; set; }
        public int MaHoaDon { get; set; }
        public string MaLoaiCP { get; set; }
        public Nullable<int> SoChiSoCu { get; set; }
        public Nullable<int> SoChiSoMoi { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblLoaiChiPhi tblLoaiChiPhi { get; set; }
    }
}
