//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDon()
        {
            this.tblCTHoaDons = new HashSet<tblCTHoaDon>();
        }
    
        public int MaHoaDon { get; set; }
        public int MaPhong { get; set; }
        public byte Thang { get; set; }
        public short Nam { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCTHoaDon> tblCTHoaDons { get; set; }
        public virtual tblPhong tblPhong { get; set; }
    }
}
