//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhoDoNoiThat
    {
        public int MaDo { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public string TenDo { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual tblPhong tblPhong { get; set; }
    }
}
