//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKiemTraPhong
    {
        public int MaKiemTra { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string MaNhanVien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblPhong tblPhong { get; set; }
    }
}
