//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhatKyTruyCap
    {
        public int MaNhatKy { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string LoaiTruyCap { get; set; }
    
        public virtual tblNguoiDung tblNguoiDung { get; set; }
    }
}
