//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.tblKiemTraPhongs = new HashSet<tblKiemTraPhong>();
        }
    
        public string MaNhanVien { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string Ten { get; set; }
        public string ChucVu { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaToaNhaDuocPhanCong { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKiemTraPhong> tblKiemTraPhongs { get; set; }
        public virtual tblNguoiDung tblNguoiDung { get; set; }
        public virtual tblToaNha tblToaNha { get; set; }
    }
}
