//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToaNha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblToaNha()
        {
            this.tblNhanViens = new HashSet<tblNhanVien>();
            this.tblTangs = new HashSet<tblTang>();
            this.tblThongKeDoanhThus = new HashSet<tblThongKeDoanhThu>();
        }
    
        public int MaToaNha { get; set; }
        public string TenToaNha { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SoTang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhanVien> tblNhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTang> tblTangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblThongKeDoanhThu> tblThongKeDoanhThus { get; set; }
    }
}
