//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongKeDoanhThu
    {
        public int MaThongKe { get; set; }
        public int MaToaNha { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal TongTienPhong { get; set; }
        public decimal TongTienDien { get; set; }
        public decimal TongTienNuoc { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
        public Nullable<System.DateTime> NgayThongKe { get; set; }
    
        public virtual tblToaNha tblToaNha { get; set; }
    }
}
