//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doannhom4CongngheNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYeuCauBaoTri
    {
        public int MaYeuCau { get; set; }
        public string MaSV { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public string TrangThai { get; set; }
        public string SoPhong { get; set; }
    
        public virtual tblPhong tblPhong { get; set; }
        public virtual tblSinhVien tblSinhVien { get; set; }
    }
}
